# Generated by Django 4.0.5 on 2022-07-14 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='T_User',
            fields=[
                ('U_Id', models.AutoField(primary_key=True, serialize=False)),
                ('U_FirstName', models.CharField(max_length=150)),
                ('U_LastName', models.CharField(max_length=150)),
                ('U_Tel', models.CharField(max_length=150)),
                ('U_Statut', models.CharField(choices=[('autre', 'autre'), ('professionnel(le)', 'Professionnel(le)'), ('personnel(le)', 'Personnel(le)')], max_length=120)),
                ('U_Email', models.EmailField(max_length=254)),
                ('U_Pwd', models.CharField(max_length=150)),
                ('U_Admin', models.BooleanField()),
                ('U_Client', models.BooleanField()),
                ('U_Supplier', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='T_Request',
            fields=[
                ('Req_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Req_Type', models.CharField(choices=[('supplier', 'Supplier'), ('admin', 'Admin')], max_length=120)),
                ('Req_Result', models.IntegerField(default=0)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_Request', to='Accounts.t_user')),
            ],
        ),
        migrations.CreateModel(
            name='T_Address',
            fields=[
                ('Adr_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Adr_Name', models.CharField(max_length=150)),
                ('Adr_Ville', models.CharField(max_length=150)),
                ('Adr_Province', models.CharField(max_length=150)),
                ('Adr_Pays', models.CharField(max_length=150)),
                ('Adr_Default', models.BooleanField()),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.t_user')),
            ],
        ),
    ]
