# Generated by Django 4.0.1 on 2022-06-18 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0011_alter_t_user_u_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_user',
            name='U_Statut',
            field=models.CharField(choices=[('autre', 'autre'), ('professionnel(le)', 'Professionnel(le)'), ('personnel(le)', 'Personnel(le)')], max_length=120),
        ),
    ]
