# Generated by Django 4.0.1 on 2022-06-14 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0011_alter_t_user_u_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_Order',
            fields=[
                ('Ord_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Ord_Type', models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin')], max_length=120)),
                ('Ord_Status', models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('inshipping', 'Inshipping'), ('ordred', 'ordred'), ('canceled', 'Canceled')], default='created', max_length=120)),
                ('Ord_Date', models.DateTimeField(auto_now_add=True)),
                ('Supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Supplier_Order', to='Accounts.t_user')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_Order', to='Accounts.t_user')),
            ],
        ),
    ]
