# Generated by Django 4.0.6 on 2022-08-01 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0001_initial'),
        ('Accounts', '0012_alter_t_user_u_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_Facture',
            fields=[
                ('Fact_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Fact_Num', models.CharField(max_length=150)),
                ('Fact_OrderCost', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('Fact_Discount', models.IntegerField()),
                ('Fact_CostFinal', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('Fact_Type', models.CharField(max_length=150)),
                ('Create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='T_Order',
            fields=[
                ('Ord_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Ord_Type', models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin')], max_length=120)),
                ('Ord_Status', models.CharField(choices=[('créée', 'Créée'), ('envoyée', 'Envoyée'), ('payée', 'Payée'), ('en livraison', 'En livraison'), ('livrée', 'Livrée')], default='envoyée', max_length=120)),
                ('Ord_Date', models.DateTimeField(auto_now_add=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_Order', to='Accounts.t_user')),
            ],
        ),
        migrations.CreateModel(
            name='T_SousOrder',
            fields=[
                ('SousOrd_Id', models.AutoField(primary_key=True, serialize=False)),
                ('SousOrd_status', models.CharField(choices=[('créée', 'Créée'), ('envoyée', 'Envoyée'), ('payée', 'Payée'), ('en livraison', 'En livraison'), ('livrée', 'Livrée')], default='envoyée', max_length=120)),
                ('SousOrd_Date', models.DateTimeField(auto_now_add=True)),
                ('expected_delivery_date', models.DateField()),
                ('real_delivery_date', models.DateField(null=True)),
                ('Ord_Id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Order.t_order')),
            ],
        ),
        migrations.CreateModel(
            name='T_OrderLigne',
            fields=[
                ('OrdLign_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Ord_Qte', models.IntegerField()),
                ('OrdLign_Status', models.CharField(choices=[('créée', 'Créée'), ('envoyée', 'Envoyée'), ('en livraison', 'En livraison'), ('livrée', 'Livrée'), ('payée', 'Payée')], default='envoyée', max_length=120, null=True)),
                ('real_delivery_date', models.DateField(null=True)),
                ('Create_at', models.DateTimeField(auto_now_add=True)),
                ('Order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Order.t_order')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.t_product')),
                ('Supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Supplier_Order', to='Accounts.t_user')),
                ('sousOrder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Order.t_sousorder')),
            ],
        ),
    ]
