# Generated by Django 4.0.6 on 2022-07-27 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_sousorder',
            name='real_delivery_date',
            field=models.DateField(default=''),
        ),
    ]
