# Generated by Django 4.0.6 on 2022-08-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_sousorder',
            name='expected_delivery_date',
            field=models.DateField(null=True),
        ),
    ]
