# Generated by Django 4.0.6 on 2022-07-27 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_alter_t_sousorder_real_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_sousorder',
            name='real_delivery_date',
            field=models.DateField(),
        ),
    ]
