# Generated by Django 4.0.1 on 2022-06-18 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0012_alter_t_user_u_statut'),
        ('Order', '0003_remove_t_order_supplier_t_orderligne_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_orderligne',
            name='OrdLign_Status',
            field=models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('inshipping', 'Inshipping'), ('ordred', 'ordred'), ('canceled', 'Canceled')], default='created', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='t_orderligne',
            name='Supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Supplier_Order', to='Accounts.t_user'),
        ),
    ]
