# Generated by Django 4.0.1 on 2022-06-18 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_t_orderligne_ordlign_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_orderligne',
            name='OrdLign_Status',
            field=models.CharField(choices=[('created', 'Created'), ('sended', 'Sended'), ('accepted', 'accepted'), ('canceled', 'Canceled')], default='created', max_length=120, null=True),
        ),
    ]
