# Generated by Django 4.0.1 on 2022-06-18 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0005_alter_t_orderligne_ordlign_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_order',
            name='Ord_Status',
            field=models.CharField(choices=[('created', 'Created'), ('sended', 'Sended'), ('paid', 'Paid'), ('inshipping', 'Inshipping'), ('ordred', 'ordred'), ('canceled', 'Canceled')], default='created', max_length=120),
        ),
    ]
