# Generated by Django 4.0.1 on 2022-09-18 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_t_productimg_t_productimgcolor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_productimgcolor',
            name='Pic_Id',
        ),
        migrations.DeleteModel(
            name='T_ProductImg',
        ),
        migrations.DeleteModel(
            name='T_ProductImgColor',
        ),
    ]
