# Generated by Django 4.0.1 on 2022-09-18 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_remove_t_productimgcolor_pic_id_delete_t_productimg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_ProductImg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(default='', max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.t_product')),
            ],
        ),
        migrations.CreateModel(
            name='T_ProductImgColor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Pic_Url', models.CharField(max_length=100)),
                ('Pic_Color', models.CharField(max_length=100)),
                ('Pic_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.t_productimg')),
            ],
        ),
    ]
